on: [push, pull_request]
name: Notify Discord

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@a858a2d186d171b5f9fed79779e5a2210678c38b
